USE Borines_Company_2
GO

DROP TABLE IF EXISTS dbo.WORKS_ON;
GO

CREATE TABLE dbo.WORKS_ON
(
	[Essn]  CHAR(9)      NOT NULL,
	[Pno]   INT          NOT NULL,
	[Hours] DECIMAL(3,1) NOT NULL,
	CONSTRAINT PK_WORKS_ON PRIMARY KEY (Essn, Pno)
     
);
GO

CREATE NONCLUSTERED INDEX IX_WORKS_ON_Hours ON dbo.WORKS_ON ([Hours] ASC);
GO

INSERT INTO dbo.WORKS_ON (Essn, Pno, Hours)
VALUES
( N'123456789', 30, 5.0 );
GO


SELECT * FROM WORKS_ON;

UPDATE dbo.WORKS_ON
SET Hours = 5.0
WHERE Essn = '123456789' AND Pno = 20;
GO

SELECT * FROM WORKS_ON;
GO

DELETE FROM WORKS_ON WHERE Essn = '123456789' AND Pno = 20;
GO

SELECT * FROM WORKS_ON;
GO
USE Borines_Company_2
GO

DROP TABLE IF EXISTS dbo.DEPT_LOCATIONS;
GO

CREATE TABLE dbo.DEPT_LOCATIONS
(
	[Dnumber]   INT         NOT NULL,
	[Dlocation] VARCHAR(15) NOT NULL,
    CONSTRAINT PK_DEPT_LOCATIONS PRIMARY KEY (Dnumber, Dlocation)
);
GO

CREATE NONCLUSTERED INDEX IX_DEPT_LOCATIONS ON dbo.DEPT_LOCATIONS ([Dnumber] ASC);
GO

INSERT INTO DEPT_LOCATIONS (Dnumber, Dlocation)
VALUES
(30, '400');
GO

SELECT * FROM DEPT_LOCATIONS;
GO

UPDATE dbo.DEPT_LOCATIONS
SET Dlocation = 'NEWLOCATION'
WHERE Dnumber = 30;
GO

SELECT * FROM DEPT_LOCATIONS;
GO

DELETE FROM DEPT_LOCATIONS WHERE Dnumber = 27 AND Dlocation = 'NEWLOCATION';
GO

SELECT * FROM DEPT_LOCATIONS;
GO


