USE Sandaga_Company
GO

DROP TABLE IF EXISTS dbo.PROJECT;
GO

CREATE TABLE dbo.PROJECT
(
 [Pname]     VARCHAR(15) NOT NULL,
 [Pnumber]   INT         NOT NULL,
 [Plocation] VARCHAR(15),
 [Dnum]      INT         NOT NULL,
 CONSTRAINT PK_PROJECT_Pnumber PRIMARY KEY (Pnumber),
 CONSTRAINT UI_PROJECT_Pname UNIQUE  (Pname)
); 
GO

CREATE NONCLUSTERED INDEX IX_PROJECT_Plocation ON dbo.PROJECT ([Plocation] ASC);
GO

INSERT INTO dbo.PROJECT (Pname, Pnumber, Plocation, Dnum)
VALUES
(N'TECHVOC', 33, N'POB.5 MIDSAYAP', 22);
GO

SELECT * FROM dbo.PROJECT;
GO

UPDATE dbo.PROJECT
SET Plocation = 'NEW LOCATION',
	Dnum = 50
WHERE Pnumber = 30;
GO

SELECT * FROM PROJECT;
GO

--LEFT JOIN between DEPARTMENT and PROJECT
SELECT D.DName, D.Dnumber, P.Pname, P.Plocation
FROM dbo.DEPARTMENT D
LEFT JOIN dbo.PROJECT P
ON D.Dnumber = P.Pnum;
GO

--RIGHT JOIN between DEPARTMENT and PROJECT
SELECT D.DName, D.Dnumber, P.Pname, P.Plocation
FROM dbo.DEPARTMENT D
RIGHT JOIN dbo.PROJECT P
ON D.Dnumber = P.Pnum;
GO

--CROSS JOIN between DEPARTMENT and PROJECT
SELECT D.DName, D.Dnumber, P.Pname, P.Plocation
FROM dbo.DEPARTMENT D
CROSS JOIN dbo.PROJECT P
GO